/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author PepetoPonk
 */
import java.io.*;
import java.util.HashMap;
import java.util.Map;
import Funcionalidad.componentes.Usuario;
import java.util.List;
import DAO.UsuarioDAO;

// O para la aproximación moderna:
/*import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;*/
import javax.swing.JOptionPane;
public class IGUL extends javax.swing.JFrame {
    
    
    private Map<String, String[]> usuariosConRol; 
    /**
     * Creates new form IGUL
     */
    public IGUL() {
        setLocationRelativeTo(null);
        this.setResizable(false); 
        initComponents();
        cargarUsuariosDesdeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cargarUsuariosDesdeArchivo() {
    usuariosConRol = new HashMap<>();
    UsuarioDAO usuarioDao = new UsuarioDAO();
    List<Usuario> listaUsuarios = usuarioDao.obtenerUsuarios();
    if(listaUsuarios != null && !listaUsuarios.isEmpty()) {
        for (Usuario u : listaUsuarios) {
            String correo = u.getCorreo();
            String contrasena = u.getContrasena();
            String rol  = u.getRol() != null ? u.getRol() : "sin_rol";
            usuariosConRol.put(correo, new String[]{contrasena, rol});
            }
        } else {
            System.out.println("Error al cargar el archivo de usuarios");
            JOptionPane.showMessageDialog(this, "Error al cargar datos de usuarios. El archivo no existe o está dañado.", "Error de Inicio", JOptionPane.ERROR_MESSAGE);
        }
    }

    
      
   //String usuario, contraseña; 
/*public void leerTexto(){
        
        String archivo = "SoloArchivos/Usuarios_contraseñas.txt"; // Ruta del archivo
       try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                // Separar usuario y contraseña por la coma
                String[] partes = linea.split(",");
                if (partes.length == 2) {
                    usuario = partes[0].trim();
                    contraseña = partes[1].trim();
                    VerificarUsuario();
                    //System.out.println("Usuario: " + usuario + " | Contraseña: " + contraseña);
                } else {
                    System.out.println("Formato incorrecto en la línea: " + linea);
                }
            }
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }*/

public void VerificarUsuario() {
        // 1. Obtener datos ingresados
        String usuarioIngresado = usu.getText().trim();
        String contrasenaIngresada = new String(contra.getPassword());

        // 2. Verificar si la clave (el correo completo) existe en el mapa
        if (usuariosConRol.containsKey(usuarioIngresado)) {
            
            // 3. Si existe, obtener el array [contraseña, rol] almacenado
            String[] datosAlmacenados = usuariosConRol.get(usuarioIngresado);
            String contrasenaAlmacenada = datosAlmacenados[0];
            String rolAlmacenado = datosAlmacenados[1];
            
            // 4. Comparar la contraseña
            if (contrasenaAlmacenada.equals(contrasenaIngresada)) {
                
                // Login Exitoso: Llamar al método de redirección con el rol
                Usuario usuario = new Usuario(usuarioIngresado, contrasenaIngresada);
                realizarLogin(rolAlmacenado, usuario);
                
            } else {
                // Error: Usuario existe, pero la contraseña es incorrecta (solo este mensaje)
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error de Acceso", JOptionPane.WARNING_MESSAGE);
            }
            
        } else {
            // Error: El usuario no fue encontrado en la lista
            JOptionPane.showMessageDialog(this, "Usuario no encontrado", "Error de Acceso", JOptionPane.WARNING_MESSAGE);
        }
    }

 private void realizarLogin(String rol, Usuario usuario) {
    // Usamos equalsIgnoreCase para ser flexibles con mayúsculas/minúsculas en el rol
    
    if (rol.equalsIgnoreCase("Dueño")) {
        
        // 1. DESCOMENTAR: Crear y mostrar la ventana de Dueño
        new DuenoFrame(usuario).setVisible(true); 
        
        // Opcional: Quita este mensaje si quieres una transición más rápida.
        // JOptionPane.showMessageDialog(this, "Bienvenido Dueño!"); 
        
        this.dispose(); // Cierra la ventana de login
        
    } else if (rol.equalsIgnoreCase("secretaria") || rol.contains("secret")) {
        
        // 2. DESCOMENTAR: Crear y mostrar la ventana de Secretaría
        new SecretariaFrame(usuario).setVisible(true);
        
        // Opcional: Quita este mensaje si quieres una transición más rápida.
        // JOptionPane.showMessageDialog(this, "Bienvenida Secretaria!"); 
        
        this.dispose();
        
    } else if (rol.equalsIgnoreCase("miembro")) {
        
        // 3. DESCOMENTAR: Crear y mostrar la ventana de Miembro
        new MiembroFrame(usuario).setVisible(true);
        
        // Opcional: Quita este mensaje si quieres una transición más rápida.
        // JOptionPane.showMessageDialog(this, "Bienvenido Miembro!"); 
        
        this.dispose();
        
    } else {
        // Mantenemos el mensaje de error para roles no asignados
        JOptionPane.showMessageDialog(this, "Usuario válido, pero sin rol asignado: " + rol);
    }
}

    // --- EVENTOS DE BOTÓN (simplificado) ---
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usu = new javax.swing.JTextField();
        Usuario2 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        BotonLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 37, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel1.setText("INICIAR SESION");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 280, 40));

        usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuActionPerformed(evt);
            }
        });
        jPanel1.add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 109, 170, -1));

        Usuario2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Usuario2.setText("contraseña:");
        jPanel1.add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 141, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, 30));

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 170, -1));
        
        BotonLogin.setBackground(new java.awt.Color(255, 0, 0));
        BotonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLoginMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout BotonLoginLayout = new javax.swing.GroupLayout(BotonLogin);
        BotonLogin.setLayout(BotonLoginLayout);
        BotonLoginLayout.setHorizontalGroup(
            BotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(BotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BotonLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BotonLoginLayout.setVerticalGroup(
            BotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(BotonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BotonLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(BotonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void BotonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLoginMouseClicked
        VerificarUsuario(); 
        //VerificarUsuario();// TODO add your handling code here:
    }//GEN-LAST:event_BotonLoginMouseClicked

    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGUL().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonLogin;
    private java.awt.Label Usuario2;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}


