/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Funcionalidad.componentes.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author d23ylan
 */
public class NotificacionGui extends javax.swing.JFrame {
    
    private DefaultTableModel modeloPorVencer;
    private DefaultTableModel modeloVencidas;
    private DefaultTableModel modeloCompletadas;
    private Usuario usuario;
    /**
     * Creates new form NotificacionGui
     */
    public NotificacionGui(Usuario usuario) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        
        this.usuario = usuario;
        
        modeloPorVencer = new DefaultTableModel(new Object[]{"Tarea", "Fecha", "Estado"}, 0);
        modeloVencidas = new DefaultTableModel(new Object[]{"Tarea", "Fecha", "Estado"}, 0);
        modeloCompletadas = new DefaultTableModel(new Object[]{"Tarea", "Fecha", "Estado"}, 0);
        
        llenarNotificaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tareasCompletadas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tareasPorVencer = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tareasVencidas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tareas por vencer");

        jLabel4.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tareas Vencidas");

        jLabel1.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tareas Completadas");

        tareasCompletadas.setBackground(new java.awt.Color(204, 255, 255));
        tareasCompletadas.setFont(new java.awt.Font("Quicksand Medium", 1, 13)); // NOI18N
        tareasCompletadas.setForeground(new java.awt.Color(0, 0, 0));
        tareasCompletadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha", "Estado"
            }
        ));
        tareasCompletadas.setGridColor(new java.awt.Color(204, 255, 255));
        tareasCompletadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tareasCompletadas);

        tareasPorVencer.setBackground(new java.awt.Color(204, 255, 255));
        tareasPorVencer.setFont(new java.awt.Font("Quicksand Medium", 1, 13)); // NOI18N
        tareasPorVencer.setForeground(new java.awt.Color(0, 0, 0));
        tareasPorVencer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha", "Estado"
            }
        ));
        tareasPorVencer.setGridColor(new java.awt.Color(204, 255, 255));
        tareasPorVencer.setSelectionBackground(new java.awt.Color(75, 75, 75));
        tareasPorVencer.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tareasPorVencer);

        tareasVencidas.setBackground(new java.awt.Color(204, 255, 255));
        tareasVencidas.setFont(new java.awt.Font("Quicksand Medium", 1, 13)); // NOI18N
        tareasVencidas.setForeground(new java.awt.Color(0, 0, 0));
        tareasVencidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha", "Estado"
            }
        ));
        tareasVencidas.setGridColor(new java.awt.Color(204, 255, 255));
        tareasVencidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tareasVencidas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Quicksand Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOTIFICACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificacionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificacionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificacionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificacionGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuario = new Usuario("JosePerez@gmail.Dueño", "12345");
                new NotificacionGui(usuario).setVisible(true);
            }
        });
    }

    public void llenarNotificaciones() {
        NotificacionFuncionalidad noti = new NotificacionFuncionalidad(usuario);
       
        modeloPorVencer.setRowCount(0);
        
        List<Tarea> tareas = noti.buscarTareasPorVencer();
        
        for (Tarea tarea : tareas) {
            modeloPorVencer.addRow(new Object[]{
                tarea.getNombre(),  // Columna 1
                tarea.getFecha(),   // Columna 2  
                tarea.getEstado()   // Columna 3
            });
        }
        tareasPorVencer.setModel(modeloPorVencer);
        
        modeloVencidas.setRowCount(0);
        
        List<Tarea> tareasVenc = noti.buscarTareasVencidas();
        
        for (Tarea tarea : tareasVenc) {
            modeloVencidas.addRow(new Object[]{
                tarea.getNombre(),  // Columna 1
                tarea.getFecha(),   // Columna 2  
                tarea.getEstado()   // Columna 3
            });
        }
        tareasVencidas.setModel(modeloVencidas);
        
        modeloCompletadas.setRowCount(0);
        
        List<Tarea> tareasCompl = noti.buscarTareasCompletadas();
        
        for (Tarea tarea : tareasCompl) {
            modeloCompletadas.addRow(new Object[]{
                tarea.getNombre(),  // Columna 1
                tarea.getFecha(),   // Columna 2  
                tarea.getEstado()   // Columna 3
            });
        }
        tareasCompletadas.setModel(modeloCompletadas);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tareasCompletadas;
    private javax.swing.JTable tareasPorVencer;
    private javax.swing.JTable tareasVencidas;
    // End of variables declaration//GEN-END:variables
}
